### ISSUE TITLE
Error in iOS paytm plugin

### ISSUE THREAD

**Issue by hari7777** [samyam-a/PayTM-PhoneGap-Plugin#1]
![error](https://cloud.githubusercontent.com/assets/13344155/9381165/a5c81010-4752-11e5-9a30-de5c77817e41.png)

I facing this issue when i add your paytm cordova plugin in my project Please help me to solve this issue i already try this from last two three weeks...

**Comment by samyam-a** [comment]
Seems like Security.framework is not included in your app. Please include it in your ios project and rebuild again.

**Comment by hari7777** [comment]
Thanks Dude :) Its working now :)

**Comment by hari7777** [comment]
and one more think i want to know, please tell where i want to change the "MID" and other things like checksum generation url  and verficatio url  after install the plugin please help me this one dude...

**Comment by samyam-a** [comment]
I would recommend just removing and adding the plugin again with the proper installation variables. This should not affect your project in any way and is simpler to do.
Incase you want to it manually, the values are in your iOS project's Info.plist
All keys are prefixed by 'PayTM'.
On Android the values are in res/values/paytmcordova.xml
keys are prefixed with 'paytm-'
